openapi: 3.0.1
info:
  title: Home Service API
  description: API for NodeJS Home service
  version: 0.0.1
servers:
  - url: http://0.0.0.0:3000/
paths:

  /login:
    get:
      summary: Requests a login with a usernme and password.
      parameters:
        - in: query
          name: userName
          description: The username of a person.
          required: true
          schema:
            type: string
        - in: query
          name: password
          description: The password of a person.
          required: true
          schema:
            type: string
      responses:
        '200':    # status code
          description: A greeting object describing the logged in user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /greet:
    get:
      summary: Returns a greeting with a name supplied.
      parameters:
        - in: query
          name: name
          description: The name of a person.
          required: true
          schema:
            type: string
      responses:
        '200':    # status code
          description: A greeting string containing the person who greeted.
          content:
            application/json:
              schema:
                type: string

  /speedHistory:
    get:
      summary: Returns a collection of internet line speed tests over a period of time.
      parameters:
        - in: query
          name: beginDate
          description: The date from which the query should run.
          required: false
          schema:
            type: string
        - in: query
          name: endDate
          description: The date to which the query should run.
          required: false
          schema:
            type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpeedHistoryResults'

  /speedTest:
    get:
      summary: Returns the current internet line speed test.
      parameters:
      - in: query
        name: type
        description: The type of a speed test.
        required: false
        schema:
          type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpeedHistoryResults'

  /currentWeather:
    get:
      summary: Returns the current weather of a location.
      parameters:
      - in: query
        name: locationKey
        description: The key of the requested location.
        required: true
        schema:
          type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                 type: string

  /searchCity:
    get:
      summary: Returns the information of a city.
      parameters:
      - in: query
        name: city
        description: The city text.
        required: true
        schema:
          type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                 type: string

  /covid19Summary:
    get:
      summary: Returns the covid19 statuses of all countries.      
      responses:
        '200':    # status code
          description: A JSON array objects containing the latest covid19 details.
          content:
            application/json:
              schema:
                 type: string

  /covid19Countries:
    get:
      summary: Returns all the county names and slugs that is giving Covid19 information.      
      responses:
        '200':    # status code
          description: A JSON array objects containing the latest covid19 country names.
          content:
            application/json:
              schema:
                 type: string
  
  /covid19DayOne:
    get:
      summary: Returns the covid19 stats since day one.      
      responses:
        '200':    # status code
          description: A JSON array objects containing the latest covid19 details.
          content:
            application/json:
              schema:
                 type: string

components:
  schemas:
    User:
      type: object
      properties:
        FirstName:
          type: string
          description: First name of the logged in User.
        LastName:
          type: string
          description: Last name of the logged in User.
        email:
          type: string
          description: The email of the logged in User.
        Role:
          type: string
          description: The security role of the logged in User.
    Covid19Summary:
      type: array
      properties:
        Country:
          type: string
          description: country name
        Slug:
          type: string
          description: web name
        NewConfirmed:
          type: string
          description: new confirmed cases in the last 24 hours
    SpeedHistoryResults:
      type: array
      properties:
        id:
          type: string
          description: blah
        time:
          type: string
          description: Recorded time of the speed test.
        uploadSpeed:
          type: number    
          description: Upload speed test result.
        downloadSpeed:
          type: number    
          description: Download speed test result.
    