openapi: 3.0.1
info:
  title: Home Service API
  description: API for NodeJS Home service
  version: 0.0.1
servers:
  - url: http://localhost:3000/
paths:
  /greet:
    get:
      summary: Returns a greeting with a name supplied.
      parameters:
        - name: name
          in: query
          description: The name of a person.
          required: true
          schema:
            type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: string             
components:
  schemas:
    Name:
      type: string
      properties:
        id:
          type: integer
        name:
          type: string